# Generated by Django 6.0.6 on 2026-06-13 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PaymentMethod', models.CharField(choices=[('M-Pesa', 'M-Pesa'), ('Airtel Money', 'Airtel Money'), ('Mixx by Yas', 'Mixx by Yas'), ('HaloPesa', 'HaloPesa'), ('Visa', 'Visa'), ('MasterCard', 'MasterCard')], max_length=50)),
                ('PaymentStatus', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Pending', max_length=20)),
                ('PaymentDate', models.DateTimeField(auto_now_add=True)),
                ('TransactionReference', models.CharField(blank=True, max_length=100)),
                ('Order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
        ),
    ]
