# Generated by Django 6.0.6 on 2026-06-25 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedPaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PaymentMethod', models.CharField(choices=[('M-Pesa', 'M-Pesa'), ('Airtel Money', 'Airtel Money'), ('Mixx by Yas', 'Mixx by Yas'), ('HaloPesa', 'HaloPesa'), ('Visa', 'Visa'), ('MasterCard', 'MasterCard')], max_length=50)),
                ('PhoneNumber', models.CharField(blank=True, max_length=20)),
                ('BankAccountNumber', models.CharField(blank=True, max_length=30)),
                ('BankName', models.CharField(blank=True, max_length=100)),
                ('ControlNumber', models.CharField(editable=False, max_length=8, unique=True)),
                ('IsDefault', models.BooleanField(default=False)),
                ('CreatedDate', models.DateTimeField(auto_now_add=True)),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='accounts.customer')),
            ],
            options={
                'ordering': ['-IsDefault', '-CreatedDate'],
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='SavedPaymentMethod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='payments.savedpaymentmethod'),
        ),
    ]
