# Generated by Django 6.0.6 on 2026-06-13 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DeliveryAddress', models.TextField()),
                ('DeliveryStatus', models.CharField(choices=[('Not Eligible', 'Not Eligible'), ('Preparing', 'Preparing'), ('In Transit', 'In Transit'), ('Delivered', 'Delivered')], default='Not Eligible', max_length=20)),
                ('Order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('ShippingZone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.shippingzone')),
            ],
        ),
    ]
